### PR TITLE
Added the pictures and training node config files

### PR DESCRIPTION
**Pull request by ravishranjan**

### CODE REVIEW

**Comment by ga-hegsvold** [comment]
Under "4.2 Import Data", step 1: "...download the Training Node - config.json file from here..."
I think it would be good to let the text "Training Node - config.json" link directly to the file in question and just skip the "from here" part. Improves quality of life for the reader.

Fixed now !

**Comment by ga-hegsvold** [comment]
Under "4.2 Import Data", step 5: "Run the pipe by hitting ctrl + Enter"
Ctrl + Enter only shows a preview. It doesn't actually run the pipe. Clicking the "Start" button does.

**Comment by ravishranjan** [comment]
Review comments are done now !

**Comment by ravishranjan** [comment]
> Under "4.2 Import Data", step 5: "Run the pipe by hitting ctrl + Enter"
> Ctrl + Enter only shows a preview. It doesn't actually run the pipe. Clicking the "Start" button does.

Fixed now !

**Comment by ga-hegsvold** [comment]
6.3.1 Merging sources: You have a good visual example of how merging works, using the person datasets. When you move on to the config example you switch to customers and orders.
Perhaps you should keep using the person datasets for continuity?

fixed and also updated the namespace identifiers section as discussed. Uploaded the lastest Json config file.

**Pull request merged**
